### ISSUE TITLE
what are ranges values of the config parameters? "? >=parameter<= ? "

### ISSUE THREAD

**Issue by Revanth-guduru-balaji** [marella/ctransformers#115]
What exactly gpu_layers config does ?

**Comment by RajarshiBhadra** [comment]
Any details on this question?

**Comment by marella** [comment]
It runs some of the model layers on GPU instead of CPU which speeds up the generation. The specific value to use depends on your hardware and model.
Start with a large value say `100` and try running it. If your GPU doesn't have enough memory to load all model layers, it will throw out of memory error and you will have to reduce (binary search) it until it works.
