### ISSUE TITLE
CuBLas Support 

### ISSUE THREAD

**Issue by TheFaheem** [marella/ctransformers#12]
Do you have any ideas to support CuBlas to increase inference speed by offloading some layers to GPU

**Comment by marella** [comment]
I'm planning to add it for LLaMA models as llama.cpp already supports it.
For other models, it requires more effort.

**Comment by TheFaheem** [comment]
It would be great if you even add it to llama models for now. For other models open source community will surely help you...

**Comment by ParisNeo** [comment]
The problems with this is preparing good prebuilt wheels so that the final user don't need to build it on his PC or Mac. But there are many combinations. At least support some standard ones would be cool.

Thank you for this binding. I added it as one of the supported bindings along with your previous ones on my GPT4All iu:
https://www.youtube.com/watch?v=ds_U0TDzbzI&ab_channel=ParisNeo

**Comment by TheFaheem** [comment]
> The problems with this is preparing good prebuilt wheels so that the final user don't need to build it on his PC or Mac. But there are many combinations. At least support some standard ones would be cool.
> 
> Thank you for this binding. I added it as one of the supported bindings along with your previous ones on my GPT4All iu: https://www.youtube.com/watch?v=ds_U0TDzbzI&ab_channel=ParisNeo

Excellent... But What GPT4All UI is Di

**Comment by ParisNeo** [comment]
Let's say it is an alternative to oobabooga and other tools :)

**Comment by marella** [comment]
Added  cuBLAS support for LLaMA models in the latest version 0.2.3

To use, install from source with cuBLAS enabled:

```sh
CT_CUBLAS=1 pip install ctransformers --no-binary ctransformers
```

and specify number of layers to run on GPU:

```py
llm = AutoModelForCausalLM.from_pretrained(..., gpu_layers=50)
```

[Run in Google Colab](https://colab.research.google.com/drive/1Ihn7iPCYiqlTotpkqa1tOhUIpJBrJ1Tp)

---

> The problems with this is preparing good prebuilt wheels so that the final user don't need to build it on his PC or Mac. But there are many combinations. At least support some standard ones would be cool.

I will see later if I can at least provide precompiled libraries for AVX2 + CUDA 12. But first I will have to check if compiling shared libraries with CUDA 12.1 will work with future 12.x versions, otherwise it will be difficult.

**Comment by TheFaheem** [comment]
Excelent Job @marella. Thanks for Adding it!
