### ISSUE TITLE
No GPU support for MPT models?

### ISSUE THREAD

**Issue by sidharthiimc** [marella/ctransformers#31]

**Comment by TheBloke** [comment]
I came here to talk about this as well

I don't know if you've seen @marella , but KoboldCpp recently added OpenCL GPU support for:
* GPT-J
* GPT-NeoX
* GPT-2 (StarCoder/WizardCoder)
* MPT

It was added in Release 1.32, and has since had a few patches: https://github.com/LostRuins/koboldcpp/releases/tag/v1.32.3

So, would it be possible to get the same in ctransformers?  

If so, this immediately brings it to @ParisNeo's LoLLMS-UI as well, and then we have two UIs with full GPU support for these non-Llama model types.

**Comment by TheBloke** [comment]
PS. Do you still use Discord, marella? My new Discord is getting very popular, and we have a room for talking about more technical things in GGML.  LostRuins (KoboldCpp dev) is there for example, and so is cmp-nct (ggllm.cpp)

Anyway if you're interested to join, we're at: https://discord.gg/theblokeai

**Comment by richardr1126** [comment]
I am wondering the same thing. Prompt processing is too slow without OpenCL.

**Comment by marella** [comment]
@TheBloke koboldcpp is GPL licensed so I can't use their code in ctransformers which is MIT licensed.
Thanks for the discord invite. I'm not very active on discord but will join.

I will see if there is an easy way to add it by following the llama.cpp and falcon (ggllm.cpp) implementations but it is going to take me time to understand them.
I'm also hoping that ggllm.cpp will implement other models similar to falcon.

**Comment by marella** [comment]
Added experimental CUDA support for MPT models in the latest version 0.2.20

When I tested on my machine and Google Colab it runs much faster.

```py
llm = AutoModelForCausalLM.from_pretrained("TheBloke/MPT-7B-GGML", gpu_layers=50)
```

Earlier it was not possible to run 30B models on Google Colab, but now they can be run by offloading some layers to GPU `gpu_layers=35`.
