### ISSUE TITLE
New ggml llamacpp file format support

### ISSUE THREAD

**Issue by ParisNeo** [marella/ctransformers#4]
Hi and thanks for this beautiful work.

Are you planning on supporting the version 2 of the llamacpp files. I want to add the OpenAssistant model to my GPT4ALL-ui and can't find a python binding that supports it.

Here is the bloke's version of the model:
https://huggingface.co/TheBloke/OpenAssistant-SFT-7-Llama-30B-GGML/tree/main

Best regards

**Comment by marella** [comment]
Hi,

Support for the new quantization format was discussed previously [here](https://github.com/marella/ctransformers/issues/1#issuecomment-1548013539). Since it is a breaking change I haven't updated yet. There are few more features I'm adding to the Python library after which I will update the C backend.

I will look into adding `llama.cpp` support over the weekend but don't know if I will be to finish it this week. I'm also waiting for the MPT [PR](https://github.com/ggerganov/ggml/pull/145) to be merged so that I can add that as well.

Thanks for the model link. Do you have a link to a smaller LLaMA-7B model quantized in the latest format that I can use for testing? My machine doesn't have enough RAM to run larger models.

**Comment by ParisNeo** [comment]
Of course,
The Bloke has you covered. He has all kinds of models in the new format:
https://huggingface.co/TheBloke

His hugging face models are well organized. Just search for GGML models on his space and you can find anything you want.

The best one is WizardLM-7B-uncensored-GGML, that you can find here:

https://huggingface.co/TheBloke/WizardLM-7B-uncensored-GGML

**Comment by marella** [comment]
This is released in the latest version [0.2.0](https://github.com/marella/ctransformers/releases/tag/v0.2.0)

It supports LLaMA, MPT models now. It also includes the most recent breaking change https://github.com/ggerganov/llama.cpp/pull/1508
