### ISSUE TITLE
`Fatal Python error: Illegal instruction` when running on MacOS

### ISSUE THREAD

**Issue by vemonet** [marella/ctransformers#73]
Hi, I am using CTransformers with LangChain to perform inference on Llama 2 (https://huggingface.co/TheBloke/Llama-2-7B-Chat-GGML)

When running tests on GitHub Actions it works on Linux and Windows, but not MacOS, giving the error:

```bash
Fatal Python error: Illegal instruction

Current thread 0x0000000101bf8600 (most recent call first):
  File "python3.11/site-packages/ctransformers/llm.py", line 207 in __init__
  File "python3.11/site-packages/ctransformers/hub.py", line 157 in from_pretrained
  File "python3.11/site-packages/langchain/llms/ctransformers.py", line 73 in validate_environment
```

Which seems to be when CTransformers create the LLM: https://github.com/marella/ctransformers/blob/main/ctransformers/llm.py#L207

```python
     self._llm = self._lib.ctransformers_llm_create(
            model_path.encode(),
            model_type.encode(),
            config.context_length,
            config.gpu_layers,
        )
```

Workflow run failing: https://github.com/vemonet/libre-chat/actions/runs/5694749918/job/15436518518

Any idea why this fails only on Mac? Is it due to the file I downloaded? Wrong format, wrong encoding? Because it seems like `ctransformers` is tested successfully on MacOS using GitHub Action, so the environment should not be the problem

**Comment by marella** [comment]
Hi, looks like this run was from a week ago and using an older version of ctransformers, so if you update to latest version it should work.
In older versions of ctransformers, AVX2 instructions were used by default but GitHub Actions for macOS run on old CPU which don't support them and causing this error. In my [workflow](https://github.com/marella/ctransformers/blob/bb4e134a8fe5fd51230adc669e66e3eb6216b7ed/.github/workflows/tests.yml#L31-L33) I exclude AVX2 for macOS. So in older versions the fix was to pass `lib="avx"` to tell it to not use AVX2.
In recent versions (0.2.17 or newer) it automatically selects AVX2/AVX based on CPU.

**Comment by vemonet** [comment]
Hi @marella , thanks for the quick answer, indeed I just ran it too soon. It works without issue with >=0.2.17

Thanks a lot for the great work!
